set test "Match line after double match"

# pdfgrep currently prints a line with two matches twice. This is of course not
# grep compatible and should be changed in the future.

# Nevertheless, right now it's the documented behaviour and should be tested
# for.

# This case tests specifically for a bug where a line after a double match would
# not be printed.

clear_pdfdir
set pdf [mkpdf regex {
    foofoo\\
    foo test
}]


pdfgrep_expect foo $pdf \
"foofoo
foofoo
foo test"

######################################################################

# This behaviour of repeating the same line over and over again is clearly not
# optimal, but it's better than an infinite loop!

set test "Empty pattern"

set empty [mkpdf empty {
    abc
}]

set timeout 2
pdfgrep_expect "" $empty \
    "abc
abc
abc"
